### ISSUE TITLE
Display icon only with hidden name

### ISSUE THREAD

**Issue by kajmaj** [GeorgeSG/lovelace-time-picker-card#34]
Hello, would it be possible to hide name but show icon only?

**Comment by jchhenderson** [comment]
I would love to see this as well.

tbh, also name without icon

**Comment by GeorgeSG** [comment]
Hi @kajmaj and @jchhenderson.

This is a very very late response 😅 , but both are possible with the `hide` option:

```yaml
# show only icon
- type: custom:time-picker-card
  entity: input_datetime.test_date_time
  layout:
    name: inside
  hide:
    name: true
# show only name
- type: custom:time-picker-card
  entity: input_datetime.test_date_time
  layout:
    name: inside
  hide:
    icon: true
```

<img width="511" alt="image" src="https://user-images.githubusercontent.com/2514425/199715437-3fab89e8-4ac3-4a67-bd12-00442ad4566d.png">

**Comment by GeorgeSG** [comment]
Hm, that's strange. I just released [Version 1.3.0](https://github.com/GeorgeSG/lovelace-time-picker-card/releases/tag/1.3.0) that refactors part of that logic. Let me know if this fixes your problem.

**Comment by jchhenderson** [comment]
1.3.0 makes no difference.  I am running HA in docker of that helps at all?

**Comment by GeorgeSG** [comment]
@jchhenderson I am unable to reproduce this in 1.3.0

Here are some example configs and screenshots from my test environment:

<img width="506" alt="Screenshot 2022-11-03 at 19 13 35" src="https://user-images.githubusercontent.com/2514425/199789592-e12929e7-aa22-4075-94a7-9d1ca61073aa.png">

```yaml
- type: custom:time-picker-card
  entity: input_datetime.test_date_time
  layout:
    name: inside
```

---

<img width="499" alt="Screenshot 2022-11-03 at 19 15 20" src="https://user-images.githubusercontent.com/2514425/199789812-a8d6fed5-3794-43d7-b3c5-701ad3ff83c2.png">

```yaml
- type: custom:time-picker-card
  entity: input_datetime.test_date_time
  layout:
    name: inside
    align_controls: right
  hide:
    icon: true
```

---

<img width="505" alt="Screenshot 2022-11-03 at 19 16 07" src="https://user-images.githubusercontent.com/2514425/199790031-7afc4dcf-c34c-4d49-bd75-18665ab9013f.png">

```yaml
- type: custom:time-picker-card
  entity: input_datetime.test_date_time
  layout:
    name: inside
  hide:
    icon: true
    name: true
```
