### ISSUE TITLE
Add tap action when embedded in entities

### ISSUE THREAD

**Issue by OToussaint** [GeorgeSG/lovelace-time-picker-card#38]
I'd like to be able to use the 
```
double_tap_action:
  action: ...
```
And also, `tap_action` as well as `hold_action `when the card is embedded (but not only?) in an entities card like so:

```
type: entities
entities:
  - type: custom:time-picker-card
    entity: input_datetime.shower
    name: Time to shower, kids
    hour_mode: 24
    link_values: true
    layout:
      name: inside
      align_controls: right
      embedded: true
    double_tap_action:
      action: call-service
      service: automation.trigger
      data:
        entity_id: automation.time_to_shower
```

This to be able to trigger my linked automation on demand.
