### ISSUE TITLE
Need update for borders in HA 2022.11.0 when embedded

### ISSUE THREAD

**Issue by OToussaint** [GeorgeSG/lovelace-time-picker-card#43]
### Checklist:

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

### The problem

In the new HA UI, a border is shown when used as embedded.
This should be removed.

### Environment

frontend==20221031.0
homeassistant==2022.11.0b5

- time-picker-card release with the issue: Not relevant
- Last working time-picker-card release (if known): Not relevant
- Browser and Operating System: Edge, Windows 10

### Problem-relevant configuration

```
- type: entities
  entities:
    - type: custom:time-picker-card
      entity: input_datetime.shower
      name: Shower time
      hour_mode: 24
      link_values: true
      hide:
        icon: true
      layout:
        name: inside
        align_controls: right
        embedded: true
```

### Javascript errors shown in the web inspector (if applicable):
Not applicable

Workaround, using card-mod

```
      style: |
        ha-card {
          border: none;
        }

```
