### ISSUE TITLE
Background color not displaying correctly

### ISSUE THREAD

**Issue by dave0111** [GeorgeSG/lovelace-time-picker-card#51]
### Checklist:

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

### The problem

When selecting Embedded from layout menu, card blends in with HA background;
TPC doesn't pick up correct card background color.

### Environment

TPC v: 1.4.0
HA OS: 10.3
HA Core: 2023.6.3 

- time-picker-card release with the issue: 1.4.0
- Last working time-picker-card release (if known):
- Browser and Operating System: Chrome/MacOS

### Problem-relevant configuration

```yaml
type: custom:time-picker-card
entity: input_datetime.next_sunset
hour_mode: 24
hour_step: 1
minute_step: 5
layout:
  hour_mode: double
  align_controls: right
  name: header
  embedded: true
hide:
  seconds: true
```

### Javascript errors shown in the web inspector (if applicable):

```

```
