### ISSUE TITLE
Actions don't work?

### ISSUE THREAD

**Issue by KVinS** [GeorgeSG/lovelace-time-picker-card#57]
### Checklist:

- [ ] I updated to the latest version available
- [ ] I cleared the cache of my browser

### The problem

Hello. I am using 2024.8.0 and mobile app/website. I still can't get any of the actions to work. (Click, double click, long click.) Could you please check if everything is ok or if I am doing something wrong? Thanks.

**Comment by GeorgeSG** [comment]
Can confirm that actions don't work from the editor :/ 

I spent some time looking into it, but couldn't get it to work. I'm attempting to use the built-in `ha-form` which the built-in cards use, but it is undocumented and there is something off.

Actions work when configured via yaml.

**Comment by ThomasHeinrichSchmidt** [comment]
Yes, actions work when configured via yaml, e.g. starting a script by using hold action works like this:
```
hold_action:
  action: call-service
  service: script.start_party_timer
  metadata: {}

```

**Comment by afkdk** [comment]
**Great card if I can make it work; I would like it to schedule a time (the next day) for starting the washer.**
This will be triggered by the time trigger and tested for actual activation by checking the boolean.

_**It seems likely the same problem as above so I have chosen to add it here; I am just not calling a service but "just toggling a boolean".**_

I am newbie in this respect, so I have added the two seemingly similar methods for toggling the input_boolean?
I have primarily used the latter as it seems most UI supported but the former also popped up in yaml editing - and seems to be accepted?

```
type: custom:time-picker-card
entity: input_datetime.start_washer_timer
hour_mode: 24
hour_step: 1
minute_step: 5
layout:
  hour_mode: double
  align_controls: center
  name: inside
  embedded: true
  thin: true
hide:
  seconds: true
name: "Start vaskemaskinen:"
tap_action:
  - action: input_boolean.start_washer_toggle
  - action: input_boolean.toggle
    target:
      entity_id:
        - input_boolean.start_washer_toggle
```

![Image](https://github.com/user-attachments/assets/3668246e-6616-4991-844d-7d72c6cec003)


**### _RESULT: The toggle action is never executed 😣_**

_And then an extra question (not covered by an example in the docs)_

I would like the color of the icon to reflect the state of this input_boolen - is that possible?

TIA
Edits: Added some, incl. image of the card as rendered - looking good but not working in respects of the tap action

**Comment by UKenGB** [comment]
> Yes, actions work when configured via yaml, e.g. starting a script by using hold action works like this:
> 
> ```
> hold_action:
>   action: call-service
>   service: script.start_party_timer
>   metadata: {}
> ```

Well I have to say, this has got me completely stumped. My tap action is:-

```
tap_action:
  action: call-service
  service: input_text.set_value
  target:
    entity_id: input_text.some_name
  data:
    value: some text
```

but just get an error:-

`Failed to perform the action input_text/set_value. required key not provided @ data|'value]`

I have moved the data: section around in case that would make a difference, but it doesn't.

The error rather makes me think there's a bug that means the data value is not being passed to the action being called.

Anyone managed to get something simple like this tap action working?
